name: API Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  # Mogelijkheid om handmatig de workflow te triggeren
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      # MySQL service container voor database tests
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: testing
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
    - uses: actions/checkout@v3

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        extensions: mbstring, dom, fileinfo, mysql, gd, curl, zip, xml
        coverage: xdebug

    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"

    - name: Install Composer dependencies
      run: composer install --no-interaction --prefer-dist --optimize-autoloader

    - name: Generate key
      run: php artisan key:generate

    - name: Directory permissions
      run: chmod -R 777 storage bootstrap/cache

    - name: Run migrations
      env:
        DB_CONNECTION: mysql
        DB_HOST: 127.0.0.1
        DB_PORT: 3306
        DB_DATABASE: testing
        DB_USERNAME: root
        DB_PASSWORD: password
      run: php artisan migrate --force

    - name: Run API tests
      env:
        DB_CONNECTION: mysql
        DB_HOST: 127.0.0.1
        DB_PORT: 3306
        DB_DATABASE: testing
        DB_USERNAME: root
        DB_PASSWORD: password
      run: php artisan test --testsuite=Feature

    # Stuur Slack notificatie bij succes of falen
    - name: Slack Notification on Success
      if: success()
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        SLACK_CHANNEL: ci-cd
        SLACK_COLOR: good
        SLACK_ICON: https://github.com/rtCamp.png?size=48
        SLACK_MESSAGE: 'API Tests geslaagd :white_check_mark:'
        SLACK_TITLE: Succesvolle API Tests
        SLACK_USERNAME: GitHub Actions

    - name: Slack Notification on Failure
      if: failure()
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        SLACK_CHANNEL: ci-cd
        SLACK_COLOR: danger
        SLACK_ICON: https://github.com/rtCamp.png?size=48
        SLACK_MESSAGE: 'API Tests gefaald :x:'
        SLACK_TITLE: Gefaalde API Tests
        SLACK_USERNAME: GitHub Actions
